export const PATHS = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",

  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    PROFILE: "/admin/profile",
    COMPLAINTS: "/admin/complaints",
    COMPLAINT_OCR: "/admin/complaints/ocr",
    DUE_ASSIGNMENTS: "/admin/assignments/due",
    COMPLAINT_DETAIL: (id: string) => `/admin/complaints/${id}`,
    NEW_COMPLAINT: "/admin/complaints/new",
    COMPLAINT_EDIT: (id: string) => `/admin/complaints/${id}/edit`,
    COMPLAINT_RESPONSE: (id: string) => `/admin/complaints/${id}/response`,
    COMPLAINT_REASSIGN: (id: string) => `/admin/complaints/${id}/reassign`,
    COMPLAINT_URGENCY: (id: string) => `/admin/complaints/${id}/urgency`,
    COMPLAINT_ARCHIVE: (id: string) => `/admin/complaints/${id}/archive`,
    USERS: "/admin/users",
    NEW_USER: "/admin/users/create",
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    COMPLAINT_TYPES: "/admin/complaint-types",
    RECEPTION_METHODS: "/admin/reception-methods",
    DEPARTMENTS: "/admin/departments",
    LETTER_TEMPLATES: "/admin/letter-templates",
    LETTER_TEMPLATE_NEW: "/admin/letter-templates/new",
    LETTER_TEMPLATE_EDIT: (id: string) => `/admin/letter-templates/${id}/edit`,
    LETTER_SETTINGS: "/admin/letter-settings",
    SOCIAL_MONITORING: "/admin/social-monitoring",
    SETTINGS: "/admin/settings",
    REPORTS: {
      DASHBOARD: "/admin/reports",
      DELAYS: "/admin/reports/delays",
      CUSTOM: "/admin/reports/custom",
      SCHEDULED: "/admin/reports/scheduled",
      ON_DEMAND: "/admin/reports/on-demand",
      MEMO: "/admin/reports/memo",
    },
    ANALYTICS: "/admin/analytics",
  },

  USER: {
    DASHBOARD: "/user/dashboard",
    PROFILE: "/user/profile",
    COMPLAINTS: "/user/complaints",
    COMPLAINT_OCR: "/user/complaints/ocr",
    DUE_ASSIGNMENTS: "/user/assignments/due",
    COMPLAINT_DETAIL: (id: string) => `/user/complaints/${id}`,
    NEW_COMPLAINT: "/user/complaints/new",
    COMPLAINT_EDIT: (id: string) => `/user/complaints/${id}/edit`,
    COMPLAINT_RESPONSE: (id: string) => `/user/complaints/${id}/response`,
    COMPLAINT_REASSIGN: (id: string) => `/user/complaints/${id}/reassign`,
    COMPLAINT_URGENCY: (id: string) => `/user/complaints/${id}/urgency`,
    COMPLAINT_ARCHIVE: (id: string) => `/user/complaints/${id}/archive`,
    SOCIAL_MONITORING: "/user/social-monitoring",
    SETTINGS: "/user/settings",
    REPORTS: {
      DASHBOARD: "/user/reports",
      DELAYS: "/user/reports/delays",
      CUSTOM: "/user/reports/custom",
      SCHEDULED: "/user/reports/scheduled",
      ON_DEMAND: "/user/reports/on-demand",
      MEMO: "/user/reports/memo",
    },
    ANALYTICS: "/user/analytics",
  },

  SUPER_ADMIN: {
    DASHBOARD: "/super-admin/dashboard",
    PROFILE: "/super-admin/profile",
    USERS: "/super-admin/users",
    NEW_USER: "/super-admin/users/create",
    USER_DETAIL: (id: string) => `/super-admin/users/${id}`,
    SETTINGS: "/super-admin/settings",
  },

  NOTIFICATIONS: {
    ADMIN: "/admin/notifications",
    SUPER_ADMIN: "/super-admin/notifications",
    USER: "/user/notifications",
  },

  UNAUTHORIZED: "/403",
  NOT_FOUND: "/404",
  PRESENT: "/present",
} as const;
